Development
evaveskova/Apple_Clone pull request #1
Opened 2019-07-12 19:29 UTC by evaveskova

2019-07-14 19:09 UTC, mosaaleb requested changes
### Hi @evaveskova :wave:,
#### Great job with the project. The UI is clean and well structured :clap:.

Also, your use of flex positioning is super :100: . 

I have added some comments to handle first before merging.

- [ ] Make sure to use [stickler](https://github.com/microverseinc/linters-config) linter to ensure that we follow the styling guidelines for writing code. You can also install html & css linters in your preferred code editor to make sure all things are good locally before your push your code. DM me on slack if you are not sure how to do this.

Let's make that all requirements are done. Then please submit a new code review.
### Happy coding. :woman_technologist:

2019-07-14 19:09 UTC, mosaaleb commented on index.html
> +                  <img class="small" src="https://web.archive.org/web/20140301004610im_/http://images.apple.com/home/images/your_verse_subhead_small.png" width="980" height="82" alt="Everyone has som
These images are links, let's add links around them.

2019-07-14 19:09 UTC, mosaaleb commented on index.html
> +          <div class="promo-image-2">
The four promo images are also links.

2019-07-14 19:09 UTC, mosaaleb commented on index.html
> +                  <img src="https://raw.githubusercontent.com/eapenzacharias/backgrounds-gradients/master/assets/usa.png" alt="#">
Let's make sure that all the `alt` tags have descriptive name in case the image can't be loaded.

2019-07-14 19:27 UTC, mosaaleb requested changes

2019-07-14 19:27 UTC, mosaaleb commented on index.html
> +      <div class="flex-container">
Let's use here semantic tags. Semantic tags serve a purpose not only for readability, but also for search engines. We can use `main` instead of `div.flex-container`

2019-07-14 19:27 UTC, mosaaleb commented on style.css
> +    flex: 1 1 calc(25% - 4px);
Very nice :clap:

2019-07-14 19:34 UTC, mosaaleb commented on index.html
> +          <div class="promo-image-3">
Since all the promo links have the same styling except for the image-url, we can reuse the same styles for all images. So all the promo images will have two classes one for the `background-url` and another one for general styling. This way we ensure that we don't have duplicated code.

2019-07-14 19:44 UTC, mosaaleb commented on style.css
> +.medium:hover {
When using `hover` on any element, it inherits the styling from that element. So you don't have to repeat the code again, unless you are overriding or appending styles.

2019-07-15 23:40 UTC, mosaaleb requested changes
### Hi @evaveskova 

Thank you for working on the suggested edits :+1:. But we still have a little work to do, here's a checklist to keep you organized:

- [ ] The promo images needs to be clickable, I noticed that you have added the links inside the `divs`, but we need the `a` tag to be surrounding each `div`.
- [ ] Make sure to use [stickler](https://github.com/microverseinc/linters-config) and since all we have are `html` and `css` files, we need only to allow the `style lint` in `.stickler.yml` file. This is a very good way to ensure that we have healthy style guidelines and no typos. You can also install `style lint` extension on your preferred text editor to make sure that all files are good before pushing.

Please, submit a new code review once you finish these requirements.

Happy coding.

2019-07-16 15:18 UTC, evaveskova commented
> ### Hi @evaveskova
> Thank you for working on the suggested edits 👍. But we still have a little work to do, here's a checklist to keep you organized:
> 
> * [ ]  The promo images needs to be clickable, I noticed that you have added the links inside the `divs`, but we need the `a` tag to be surrounding each `div`.
> * [ ]  Make sure to use [stickler](https://github.com/microverseinc/linters-config) and since all we have are `html` and `css` files, we need only to allow the `style lint` in `.stickler.yml` file. This is a very good way to ensure that we have healthy style guidelines and no typos. You can also install `style lint` extension on your preferred text editor to make sure that all files are good before pushing.
> 
> Please, submit a new code review once you finish these requirements.
> 
> Happy coding.

Once I wrap the div inside an a tag all my photos disappear. As well as that, to my knowledge, it's not good practice to wrap a div within an a tag or equivalent. Is there another solution to this? I can't seem to find one.

2019-07-16 17:16 UTC, mosaaleb approved these changes
## Great Job @evaveskova :100: 

You can now merge into mater branch :+1: 

Good luck with the next projects. Happy coding.

2019-07-16 22:53 UTC, merged